[package]
name = "noctua-cosmic"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
# Referenz auf unseren Core
noctua-core = { path = "../../core" }

# UI & App Execution
tokio = { version = "1.48.0", features = ["full"] }
clap = { version = "4", features = ["derive"] }
open = "5.3.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# Localization & Assets
i18n-embed = { version = "0.16", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.10"
rust-embed = "8.8.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
rev = "87ab8179e1bd9880239c340855ae8862034bd0e8"
features = [
    "a11y",
    "about",
    "dbus-config",
    "multi-window",
    "single-instance",
    "tokio",
    "winit",
    "wayland",
    "wgpu",
    "xdg-portal",
]
